name: Chief Marketing Engineer
favicon: null
layout_spectrum: 0.03933565993793309
typography_spectrum: 0.6336539057083428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74951360-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7290890805888921
  lightness: 0.6591720776632428
  saturation: 0.11488667107187212
  rhythmicContrast: 0.4485789823811501
purpose: []
